#:kivy 1.1.0

<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancelar"
                on_release: root.cancel()

            Button:
                text: "Ok"
                on_release: root.load(filechooser.path, filechooser.selection)
